### ISSUE TITLE
Задачи для аналитика

### ISSUE THREAD

**Issue by Pavyk96** [Pavyk96/analyst#1]
1. Составить карту эмпатии для Целевой Аудитории (_ЦА_)
2. Составить опрос для _ЦА_
3. Сравнение с конкурентами 

_Дедлайн 25.10.2023_

**Comment by Daniil-Leshchev** [comment]
Карта эмпатии для ЦА: https://miro.com/app/board/uXjVNYcK-IM=/

**Comment by Daniil-Leshchev** [comment]
https://drive.google.com/drive/folders/1BoZ8XgJgPMkQrJ41wEEUJc80KBDBLKVp?usp=sharing
