### ISSUE TITLE
Сделать выводы Аналитику

### ISSUE THREAD

**Issue by Pavyk96** [Pavyk96/analyst#2]
**Сделать следующие задачи:**

1. Сделать вывод по аналитике
2. Составить советы команде на основе вопроса

**Comment by Daniil-Leshchev** [comment]
Выводы по всем-всем исследованиям и опросам:
https://www.notion.so/danil-leshchev/439ab61c6d074296b3bcbf9ee6b9c705?pvs=4

**Comment by Daniil-Leshchev** [comment]
Тут будут рекомендации команде по тому, что нужно отразить в нашей игре:
https://www.notion.so/danil-leshchev/7d1543f7d2bf40f088acb85942352fea?pvs=4
